[project]
authors = ["Supayield"]
entry = "vault_logic.sw"
license = "Apache-2.0"
name = "fuel-contracts"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
