import React from "react";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { Toaster } from "react-hot-toast";
import { QueryClientProvider } from "@tanstack/react-query";
import { FuelProvider } from "@fuels/react";
import { queryClient, fuelConfig } from "@/lib/fuel";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background",
          `${geistSans.variable} ${geistMono.variable} font-regular`
        )}
        suppressHydrationWarning
      >
        <QueryClientProvider client={queryClient}>
          <FuelProvider fuelConfig={fuelConfig}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              <main className="mx-auto h-auto w-[85vw] sm:container">
                {children}
              </main>
              <Footer />
              <Toaster />
            </ThemeProvider>
          </FuelProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
